spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blurb_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: charlie
    password: 1331
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  #    hibernate:
  #      ddl-auto: create
